services:
  - name: othello-redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all internal traffic

  - name: othello-web
    type: web
    plan: free
    env: docker
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: othello-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - name: othello-worker
    type: worker
    plan: free
    env: docker

    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: othello-redis
          property: connectionString
      - key: SERVICE_TYPE
        value: worker
